packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.9
  "@tanstack/react-query-devtools": ^5.51.11
  "@trpc/client": ^11.0.0-rc.466
  "@trpc/react-query": ^11.0.0-rc.466
  "@trpc/server": ^11.0.0-rc.466
  eslint: ^9.6.0
  prettier: ^3.3.2
  typescript: ^5.5.3
  zod: ^3.23.8
  bcrypt-edge: ^0.0.6
  recharts: ^2.12.7
  tailwindcss: ^3.4.4
  superjson: ^2.2.1
  formik: ^2.4.6
  "framer-motion": ^11.2.3
  "@descope/node-sdk": ^1.6.9
  "@descope/react-sdk": ^2.0.56
  "@descope/nextjs-sdk": ^0.0.16
  inngest: ^3.21.1
  date-fns": ^3.6.0"
  next-plausible": ^3.12.0
  next-intl": ^3.15.3
catalogs:
  uploadthing:
    "@uploadthing": ^6.10.4
    "@uploadthing/react": ^6.5.4
  vercel:
    "hypertune": ^2.3.8
    "@vercel/otel": ^1.9.1
    "@vercel/analytics": ^0.9.0
    "@vercel/edge-config": ^1.2.0
    "@vercel/blob": ^0.23.4
  react18:
    react: 18.3.1
    "react-dom": 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
  ui:
    "@tanstack/react-table": ^8.19.2
    "flowbite": 1.7.0
    "flowbite-react": ^0.10.1
    "@mui/material": ^5.16.4
    "@mui/material-nextjs": ^5.16.4
    "@mui/icons-material": ^5.16.4
    "@mui/styled-engine-sc": 6.0.0-alpha.18
    "@emotion/styled": ^11.13.0
    "@emotion/react": ^11.13.0
    "@emotion/cache": ^11.13.0
