packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.9
  "@tanstack/react-query-devtools": ^5.51.11
  "@trpc/client": ^11.0.0-rc.466
  "@trpc/react-query": ^11.0.0-rc.466
  "@trpc/server": ^11.0.0-rc.466
  eslint: ^9.6.0
  prettier: ^3.3.2
  typescript: ^5.5.3
  zod: ^3.23.8
  bcrypt-edge: ^0.0.6
  tailwindcss: ^3.4.4
  superjson: ^2.2.1
  "@descope/node-sdk": ^1.6.9
  "@descope/react-sdk": ^2.0.56
  "@descope/nextjs-sdk": ^0.0.16
catalogs:
  vercel:
    "@vercel/otel": ^1.9.1
    "@vercel/analytics": ^0.9.0
    "@vercel/edge-config": ^1.2.0
    "@vercel/blob": ^0.23.4
  react18:
    react: 18.3.1
    "react-dom": 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
  mui:
    "@mui/material": ^5.16.4
    "@mui/material-nextjs": ^5.16.4
    "@mui/icons-material": ^5.16.4
    "@mui/styled-engine-sc": 6.0.0-alpha.18
    "@emotion/styled": ^11.13.0
    "@emotion/react": ^11.13.0
    "@emotion/cache": ^11.13.0
