packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.51.9
  "@tanstack/react-form": ^0.31.0
  "@tanstack/react-query-devtools": ^5.51.11
  "@trpc/client": ^11.0.0-rc.466
  "@trpc/react-query": ^11.0.0-rc.466
  "@trpc/server": ^11.0.0-rc.466
  "trpc-openapi": ^1.2.0
  eslint: ^9.6.0
  prettier: ^3.3.2
  typescript: ^5.5.3
  zod: ^3.23.8
  next: ^14.2.4
  "bcrypt-edge": ^0.0.6
  uuid: ^10.0.0
  "@types/uuid": ^10.0.0
  recharts: ^2.12.7
  "tailwindcss-animate": ^1.0.7
  tailwindcss: ^3.4.4
  "@svgr/webpack": ^8.1.0
  superjson: ^2.2.1
  formik: ^2.4.6
  "framer-motion": ^11.2.3
  "@descope/node-sdk": ^1.6.9
  "@descope/react-sdk": ^2.0.56
  "@descope/nextjs-sdk": ^0.0.23
  inngest: ^3.21.1
  "date-fns": ^3.6.0
  "next-plausible": ^3.12.0
catalogs:
  store:
    "@reduxjs/toolkit": ^2.2.0
    "react-redux": ^9.1.0
  uploadthing:
    "@uploadthing": ^6.10.4
    "@uploadthing/react": ^6.5.
  language:
    "react-i18next": ^15.0.1
    "next-i18next": ^15.3.1
    "react-cookie": ^7.2.0
    "i18next": ^23.14.0
    "next-i18n-router": ^5.5.1
    "i18next-resources-to-backend": ^1.2.1
    "i18next-browser-languagedetector": ^8.0.0
  vercel:
    "server-only": ^0.0.1
    "hypertune": ^2.3.8
    "@opentelemetry/sdk-logs": ^0.52.1
    "@opentelemetry/instrumentation": ^0.52.1
    "@opentelemetry/api": ^1.9.0
    "@opentelemetry/api-logs": ^0.52.1
    "@vercel/otel": ^1.9.1
    "@vercel/analytics": ^1.3.1
    "@vercel/edge-config": ^1.2.0
    "@vercel/blob": ^0.23.4
    "@vercel/kv": ^2.0.0
    "@vercel/flags": ^2.6.0
  react18:
    react: 18.3.1
    "react-dom": 18.3.1
    "@types/react": ^18.3.3
    "@types/react-dom": ^18.3.0
  ui:
    "postcss": ^8
    "autoprefixer": ^10.4.19
    "react-icons": ^5.2.1
    "@tanstack/react-table": ^8.19.2
    "flowbite": 1.7.0
    "flowbite-react": ^0.10.1
    "@mui/material": ^5.16.4
    "@mui/material-nextjs": ^5.16.4
    "@mui/icons-material": ^5.16.4
    "@mui/styled-engine-sc": 6.0.0-alpha.18
    "@emotion/styled": ^11.13.0
    "@emotion/react": ^11.13.0
    "@emotion/cache": ^11.13.0
